on: [push, pull_request]
name: Test
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Install Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.17
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Deps
              run: sudo apt install libc6-dev libglu1-mesa-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config
            - name: Test
              run: go test -tags noui ./...
